---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  namespace: development
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: httpd-service_mapping
      host: kevin-test-dev3.eureka.software
      prefix: /
      service: httpd-service.development:80
spec:
  selector:
    app: httpd
    environment: development
    role: web
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: httpd
  namespace: development
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: httpd
        environment: development
        role: web
    spec:
      containers:
      - name: httpd
        image: "httpd"
        ports:
        - containerPort: 80