apiVersion: apps/v1      # see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/
kind: Deployment           # type of object that's defined in this file
metadata:
  name: pod-httpd   # the name displayed in the first column of 'kubectl get pods'
  namespace: qa
  labels:
    app: apache_webserver  # this tag is added to help this object to link to the service object.
spec:
  replicas: 1  # specifies n number of pods to run which will be evenly distributed amongst nodes
  selector:
    matchLabels:
      app: hello-world-pod
  template:
    metadata:
      labels:
        app: hello-world-pod
    spec: # container(s) spec
      containers:
      - name: container-httpd      # name of the container that will reside in the pod
        image: httpd:latest      # using the official apache image from docker hub, along with a tag
        ports:                # this bit is purely for informational purposes only and can be omitted.
        - containerPort: 80   # what port the container will be listening on
      imagePullSecrets:
      - name: docker-registry-login-secret